### CRIAR USUARIO

POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "Matheus",
    "email": "matheus@email.com"
}

### CRIAR REFEIÇÃO
POST http://localhost:3333/meals
Content-Type: application/json
Cookie: 3a22f97e-c110-4a4f-b927-22a442687bf

{
    "name": "Sorvete",
    "description": "Sobremesa",
    "isOnDiet": false,
    "date": "2025-10-04T12:30:00Z"
}

### LISTAR REFEIÇÕES DO USUARIO
GET http://localhost:3333/meals
Cookie: 3a22f97e-c110-4a4f-b927-22a442687bf

