### CRIAR TRANSAÇÃO DE CRÉDITO
POST http://localhost:3333/transactions
Content-Type: application/json

{
  "title": "Salário",
  "amount": 5000,
  "type": "credit"
}

### CRIAR TRANSAÇÃO DE DÉBITO

POST http://localhost:3333/transactions
Content-Type: application/json

{
  "title": "Conta de Luz",
  "amount": 350,
  "type": "debit"
}

### LISTAR TRANSAÇÕES
GET http://localhost:3333/transactions

### LISTAR TRANSAÇÃO POR ID
GET http://localhost:3333/transactions/8e1d051e-9959-44f9-a6e3-c7b2e398089d

### RESUMO DE TRANSACOES
GET http://localhost:3333/transactions/summary